name: Check if periodic_jobs.yaml is valid

on:
  push:
    paths:
      - .github/workflows/periodic_jobs-check.yml
      - scripts/periodic_jobs-check.py
      - periodic_jobs.yaml

  pull_request:
    paths:
      - .github/workflows/periodic_jobs-check.yml
      - scripts/periodic_jobs-check.py
      - periodic_jobs.yaml

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install PyYAML
        run: pip3 install pyyaml

      - name: Run scripts/periodic_jobs-check.py
        run: python3 scripts/periodic_jobs-check.py

  notify-irc:
    needs: check
    runs-on: ubuntu-latest
    if: ${{ always() && github.repository_owner == 'miraheze' && ( github.ref == 'refs/heads/main' || github.event_name == 'pull_request' ) }}
    steps:
      - name: failed
        uses: technote-space/workflow-conclusion-action@v3
      - uses: rectalogic/notify-irc@v2
        if: env.WORKFLOW_CONCLUSION == 'failure'
        with:
          channel: "#miraheze-tech-ops"
          server: "irc.libera.chat"
          nickname: miraheze-github
          message: ${{ github.repository }} - ${{ github.actor }} the build has errored.
          sasl_password: ${{ secrets.IRC_MIRAHEZEBOTS }}
